### ISSUE TITLE
Multiple definition of style::normal/notice/...

### ISSUE THREAD

**Issue by Hazurl** [Jackojc/tinge#2]
`style::normal`, `style::notice`, `style::warn`, `style::error`, `style::success` are not inline or constexpr thus trigger the linker to defined them multiple times.
https://github.com/Jackojc/tinge/blob/master/tinge.hpp#L316

**Comment by Jackojc** [comment]
Fixed with 02055d29c16c0ea8e39b07a763b34e9097b5b52f, thanks for the heads up!
